"""Tests the training/evaluation *mechanics* (split, fit, predict, metrics
shape, artifact saving) against a small synthetic in-memory dataset --
not against the real sample-contract data, which is slow to build (PDF
extraction + OCR fallback checks) and would make this a slow, flaky unit
test tied to real documents changing. Real-data results belong in
docs/ml_experiment.md, generated by actually running the scripts, not
asserted here as if they were guaranteed."""
from __future__ import annotations

import json

import pytest

from ml.train_risk_classifier import _can_stratify, build_pipeline, evaluate


def _toy_dataset() -> tuple[list[str], list[str]]:
    # Deliberately separable by vocabulary so a real (not memorized-by-luck)
    # classifier should do well above the majority-class baseline.
    high = ["employee shall not compete with the company for five years"] * 6
    medium = ["the agreement may be terminated by either party without notice"] * 6
    none = [
        "this agreement is made between the parties on the date below",
        "the parties agree to act in good faith",
        "notices shall be sent to the address specified above",
        "this document is governed by the laws of the state",
        "each party bears its own costs under this agreement",
        "the schedule attached forms part of this agreement",
    ] * 2
    texts = high + medium + none
    labels = ["high"] * len(high) + ["medium"] * len(medium) + ["none"] * len(none)
    return texts, labels


def test_can_stratify_requires_at_least_two_per_class():
    assert _can_stratify(["a", "a", "b", "b"]) is True
    assert _can_stratify(["a", "a", "b"]) is False


def test_pipeline_trains_and_beats_majority_baseline_on_separable_toy_data():
    from sklearn.dummy import DummyClassifier
    from sklearn.model_selection import train_test_split

    texts, labels = _toy_dataset()
    X_train, X_test, y_train, y_test = train_test_split(
        texts, labels, test_size=0.3, random_state=0, stratify=labels
    )

    model = build_pipeline()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    baseline = DummyClassifier(strategy="most_frequent")
    baseline.fit(X_train, y_train)
    y_pred_baseline = baseline.predict(X_test)

    label_set = ["none", "high", "medium"]
    model_results = evaluate(y_test, y_pred, label_set)
    baseline_results = evaluate(y_test, y_pred_baseline, label_set)

    assert model_results["macro_f1"] >= baseline_results["macro_f1"]
    # Every label in the confusion matrix ordering appears, even with 0 support.
    assert set(model_results["per_class"].keys()) == set(label_set)


def test_evaluate_output_is_json_serializable():
    texts, labels = _toy_dataset()
    model = build_pipeline()
    model.fit(texts, labels)
    preds = model.predict(texts)
    results = evaluate(labels, preds, ["none", "high", "medium"])
    json.dumps(results)  # raises if anything (e.g. a numpy type) isn't serializable


def test_run_end_to_end_against_a_temp_dataset_file(tmp_path, monkeypatch):
    """Exercises run() itself -- the actual CLI entrypoint -- against a
    temp dataset and temp artifacts dir, so a bug in file I/O or in how
    run() wires load_dataset()/build_pipeline()/evaluate() together would
    fail here even though the pieces above test in isolation."""
    import ml.train_risk_classifier as trc

    texts, labels = _toy_dataset()
    data_path = tmp_path / "dataset.jsonl"
    with data_path.open("w") as f:
        for t, l in zip(texts, labels):
            f.write(json.dumps({"text": t, "label": l}) + "\n")

    artifacts_dir = tmp_path / "artifacts"
    monkeypatch.setattr(trc, "DATA_PATH", data_path)
    monkeypatch.setattr(trc, "ARTIFACTS_DIR", artifacts_dir)

    results = trc.run()

    assert (artifacts_dir / "risk_classifier.joblib").exists()
    assert (artifacts_dir / "results.json").exists()
    assert results["dataset"]["n_total"] == len(texts)


def test_load_dataset_raises_a_clear_error_when_missing(tmp_path, monkeypatch):
    import ml.train_risk_classifier as trc

    monkeypatch.setattr(trc, "DATA_PATH", tmp_path / "does_not_exist.jsonl")
    with pytest.raises(FileNotFoundError, match="build_dataset"):
        trc.load_dataset()
